import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { RiNextjsLine } from "react-icons/ri";
import Nav from "@/components/Nav/Nav";
import Parallax from "../components/Parallax/Parallax"
import Footer from "@/components/Footer/Footer";
import { Providers } from "../app/_GlobalRedux/Provider"
import Head from 'next/head'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <Head>
    <meta name="google-site-verification" content="MM4TstpXUw18nxudSmty14AZ5vI2ZzUqoeJAiciNxVc" />
    </Head>
    <html lang="en">
      <body className={inter.className}>
      <Providers>
      <header>
        <div className="logo"><RiNextjsLine /></div>
        <Nav />
      </header>
      <Parallax />
        <div className="main-background">
          <div className="main-content">
              {children}
          </div>
        </div>
      <Footer />
      </Providers>
      </body>
    </html>
    </>
  );
}
