import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import { RiNextjsLine } from "react-icons/ri";
import Nav from "@/components/Nav/Nav";
import Parallax from "../components/Parallax/Parallax"
import Footer from "@/components/Footer/Footer";
import { Providers } from "../app/_GlobalRedux/Provider"

const inter = Inter({ subsets: ["latin"] });

const ubuntu = Ubuntu({
  weight: ["400", "500"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  other: {
    "google-site-verification": "MM4TstpXUw18nxudSmty14AZ5vI2ZzUqoeJAiciNxVc",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <html lang="en">
      <body className={`${ubuntu.className} ${inter.className}`}>
      <Providers>
      <header>
        <div className="logo"><RiNextjsLine /></div>
        <Nav />
      </header>
      <Parallax />
        <div className="main-background">
          <div className="main-content">
              {children}
          </div>
        </div>
      <Footer />
      </Providers>
      </body>
    </html>
    </>
  );
}
